### ISSUE TITLE
What about using HJSON ?

### ISSUE THREAD

**Issue by elwinar** [elwinar/rambler#13]
I recently stumbled on https://hjson.org/.
I find it awesome and quite easier to use than JSON for things like configuration : the ability to add comments and the allowed flex in the syntax make it easier to use.

What would you think about using this from now on, with a fallback on plain old JSON for backward compatibility matters ?

@shawndellysse
@rsterbin
@cjhubert

**Comment by elwinar** [comment]
For example, the README environment example would become:

```
{
    # Useful comment about something…
    driver: mysql
    protocol: tcp
    port: 3306
    user: root
    password: ""
    database: rambler_default
    directory: migrations
    environments: {
        # Comment about the development env
        development: {
            database: rambler_development
        }
        # Comment about the testing env
        testing: {
            database: rambler_testing
        }
    }
}
```

**Comment by rsterbin** [comment]
Allowing json comments is always useful.  I'm on board with this change.

**Comment by shawndellysse** [comment]
I've known about HJSON for a while now and I've had some reservations about how far it takes JSON in the name of simplifying it. Some of the features it introduces are very nice, such as comments, unquoted keys, multi-line strings, and the implicit root object. I think it's unfortunate that the multiline syntax doesn't match the ES6 multiline string syntax, but it's nice to have. Other parts of it introduce (potential) ambiguity to the file format, such as significant whitespace and unquoted strings.

Have you considered YAML? Admittedly, it has all of the same problems that I mentioned above, but with the upside of being very well known and battle-tested. Here's that same README example YAML'd at four spaces:

```
driver: mysql
protocol: tcp
port: 3306
user: root
password: ""
database: rambler_default
directory: migrations
environments:
    development:
        database: rambler_development
    testing:
        database: rambler_testing
```
