### ISSUE TITLE
Official Docker Image

### ISSUE THREAD

**Issue by codegoalie** [elwinar/rambler#20]
We're using rambler with Kubernetes to manage out database migrations. We'd love to have an official Docker image instead of building our own. 

Currently, we are using a rambler binary built from https://github.com/elwinar/rambler/pull/19 which can read config values from the environment. Our Dockerfile is:

```Dockerfile
FROM alpine

ENV APP_HOME=/migrator
RUN mkdir -p ${APP_HOME}
WORKDIR ${APP_HOME}

COPY bin/rambler rambler
COPY rambler.json rambler.json
COPY migrations migrations

CMD ["./rambler", "apply", "-a"]
```

An example from our Docker compose file:

```yaml
version: '2'
services:
  migrator:
    build: ./migrator
    volumes:
      - "./migrator/migrations:/migrator/migrations"
    depends_on:
      - mysql
    environment:
      RAMBLER_HOST: mysql
      RAMBLER_PORT: 3306
      RAMBLER_USER: user
      RAMBLER_PASSWORD: password
      RAMBLER_DATABASE: db_name
  mysql:
    image: mysql:5.6
    volumes:
      - "/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_name
      MYSQL_USER: user
      MYSQL_PASSWORD: password
 ```

Right now, rambler will bail out when it can't find a config file, so we've only put the static, non-secret configuration in the file (driver, directory, and protocol).

The Kubernetes Job specification looks like:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: migrator
spec:
  template:
    metadata:
      name: migrator
    spec:
      containers:
      - name: migrator
        image: idnumber.dkr.ecr.us-west-2.amazonaws.com/migrator:v20161102122200
        env:
          - name: RAMBLER_HOST
            valueFrom:
              secretKeyRef:
                name: mysql-configuration
                key: host
          - name: RAMBLER_PORT
            valueFrom:
              secretKeyRef:
                name: mysql-configuration
                key: port
          - name: RAMBLER_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysql-configuration
                key: name
          - name: RAMBLER_USER
            valueFrom:
              secretKeyRef:
                name: mysql-configuration
                key: user
          - name: RAMBLER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-configuration
                key: password
      restartPolicy: Never
```

I think specifying the volume locally, like it's being done in the docker-compose file, works really well. However, I'm not sure how that would work in the actual K8s cluster. Perhaps something a [gitRepo volumes](http://kubernetes.io/docs/user-guide/volumes/#gitrepo) would work. Either way, I don't think that's a rambler concern.
