### ISSUE TITLE
PGDATABASE required for Travis CI

### ISSUE THREAD

**Issue by emmercm** [elwinar/rambler#28]
Not entirely sure why, but Travis CI does not respect either `database` out of `rambler.json` or `RAMBLER_DATABASE`.

Here's an example `.travis.yml`:

```yaml
language: go

services:
  - postgresql

addons:
  postgresql: "9.6"

go:
  - "1.10.x"

env:
  - DB_USERNAME=postgres DB_PASSOWRD= RAMBLER_USER=postgres RAMBLER_PASSWORD=

before_install:
  - cp .netrc ~
  - chmod 600 .netrc

install:
  - go get github.com/golang/lint/golint
  - go get github.com/golang/dep/cmd/dep

  - go get github.com/elwinar/rambler
  - go install github.com/elwinar/rambler

before_script:
  - psql --username postgres --command 'CREATE DATABASE countries;'

script:
  - export PGDATABASE=countries
  - rambler apply --all
  - psql --username postgres --command '\du+'
  - psql --username postgres --command '\l+'
  - psql --username postgres --dbname countries --command '\dn+'
  - psql --username postgres --dbname countries --command '\dt+'
  - psql --username postgres --dbname countries --command '\dt+ countries.'

  - dep ensure
  - go test ./... -v
  - go vet ./...
  - golint $(go list ./...)
  - go build ./cmd/server
```

Without `PGDATABASE` `rambler` uses the default `postgres` database. Setting `PGDATABASE` in `env` causes the `CREATE DATABASE` to fail:

```
$ psql --username postgres --command 'CREATE DATABASE countries;'
psql: FATAL:  database "countries" does not exist
The command "psql --username postgres --command 'CREATE DATABASE countries;'" failed and exited with 2 during .
```

I have a feeling this has to do with the connection string and an empty password for the `postgres` user.
